all:
	make --directory=server
	make --directory=client

server:
	make --directory=server
	
client:
	make --directory=client
	
shared:
	make --directory=shared

clean:
	make clean --directory=server
	make clean --directory=client
	make clean --directory=shared
